export interface Resource {
  id: string
  title: string
  description: string
  url: string
  type: 'video' | 'article' | 'course' | 'tutorial' | 'project' | 'documentation' | 'interactive'
  learningStyle: 'visual' | 'auditory' | 'reading' | 'kinesthetic'
  difficulty: 'beginner' | 'intermediate' | 'advanced'
  duration?: string
  thumbnail?: string
  category: 'tutorial' | 'project' | 'reference' | 'practice' | 'theory' | 'hands-on'
  mastery: 'introduction' | 'foundational' | 'intermediate-level' | 'advanced-level' | 'expert'
  tags: string[]
  prerequisites?: string[]
  outcomes?: string[]
  estimatedTime: number // in minutes
  isProjectBased: boolean
  isInteractive: boolean
  hasExercises: boolean
  language?: string
  framework?: string
  skillLevel: 'newbie' | 'novice' | 'intermediate' | 'advanced' | 'expert'
}

// Enhanced sample resources with comprehensive metadata
export const sampleResources: Resource[] = [
  {
    id: '1',
    title: 'Complete JavaScript Tutorial for Beginners',
    description: 'A comprehensive guide to JavaScript fundamentals with interactive examples and hands-on coding exercises',
    url: 'https://javascript.info',
    type: 'course',
    learningStyle: 'reading',
    difficulty: 'beginner',
    duration: '20 hours',
    thumbnail: '/api/placeholder/300/200',
    category: 'tutorial',
    mastery: 'foundational',
    tags: ['javascript', 'fundamentals', 'syntax', 'variables', 'functions'],
    prerequisites: ['basic HTML', 'CSS knowledge'],
    outcomes: ['Understand JavaScript syntax', 'Write basic functions', 'Handle DOM manipulation'],
    estimatedTime: 1200,
    isProjectBased: false,
    isInteractive: true,
    hasExercises: true,
    language: 'JavaScript',
    skillLevel: 'novice'
  },
  {
    id: '2',
    title: 'React Visual Learning Guide',
    description: 'Learn React through interactive diagrams, component trees, and visual examples with step-by-step illustrations',
    url: 'https://reactjs.org/tutorial/tutorial.html',
    type: 'course',
    learningStyle: 'visual',
    difficulty: 'intermediate',
    duration: '15 hours',
    thumbnail: '/api/placeholder/300/200',
    category: 'tutorial',
    mastery: 'intermediate-level',
    tags: ['react', 'components', 'jsx', 'state', 'props', 'hooks'],
    prerequisites: ['JavaScript ES6', 'HTML/CSS', 'Node.js basics'],
    outcomes: ['Build React components', 'Manage component state', 'Use React hooks'],
    estimatedTime: 900,
    isProjectBased: true,
    isInteractive: true,
    hasExercises: true,
    language: 'JavaScript',
    framework: 'React',
    skillLevel: 'intermediate'
  },
  {
    id: '3',
    title: 'Python Hands-On Project Series',
    description: 'Build real-world projects while learning Python programming - web scraping, data analysis, and automation',
    url: 'https://realpython.com',
    type: 'project',
    learningStyle: 'kinesthetic',
    difficulty: 'beginner',
    duration: '25 hours',
    thumbnail: '/api/placeholder/300/200',
    category: 'project',
    mastery: 'foundational',
    tags: ['python', 'projects', 'web-scraping', 'data-analysis', 'automation'],
    prerequisites: ['basic programming concepts'],
    outcomes: ['Build Python applications', 'Use Python libraries', 'Create automation scripts'],
    estimatedTime: 1500,
    isProjectBased: true,
    isInteractive: true,
    hasExercises: true,
    language: 'Python',
    skillLevel: 'novice'
  },
  {
    id: '4',
    title: 'Machine Learning Audio Lectures',
    description: 'Listen to expert explanations of ML concepts with detailed audio explanations and case studies',
    url: 'https://course.fast.ai',
    type: 'course',
    learningStyle: 'auditory',
    difficulty: 'intermediate',
    duration: '30 hours',
    thumbnail: '/api/placeholder/300/200',
    category: 'theory',
    mastery: 'intermediate-level',
    tags: ['machine-learning', 'ai', 'algorithms', 'statistics', 'data-science'],
    prerequisites: ['Python programming', 'Linear algebra', 'Statistics basics'],
    outcomes: ['Understand ML algorithms', 'Apply ML techniques', 'Evaluate model performance'],
    estimatedTime: 1800,
    isProjectBased: false,
    isInteractive: false,
    hasExercises: true,
    language: 'Python',
    framework: 'TensorFlow',
    skillLevel: 'intermediate'
  }
]

export function filterResourcesByStyle(resources: Resource[], style: string): Resource[] {
  return resources.filter(resource => resource.learningStyle === style)
}

export function getResourcesByTopic(topic: string): Resource[] {
  // Enhanced topic-specific resource mapping with comprehensive metadata
  const topicResources: Record<string, Resource[]> = {
    'javascript': [
      {
        id: 'js-1',
        title: 'JavaScript Fundamentals Course',
        description: 'Complete beginner guide to JavaScript programming with interactive coding exercises',
        url: 'https://javascript.info',
        type: 'course',
        learningStyle: 'reading',
        difficulty: 'beginner',
        duration: '20 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'tutorial',
        mastery: 'foundational',
        tags: ['javascript', 'fundamentals', 'syntax', 'es6', 'dom'],
        prerequisites: ['HTML basics', 'CSS basics'],
        outcomes: ['Master JavaScript syntax', 'Understand ES6 features', 'Build interactive web pages'],
        estimatedTime: 1200,
        isProjectBased: true,
        isInteractive: true,
        hasExercises: true,
        language: 'JavaScript',
        skillLevel: 'novice'
      },
      {
        id: 'js-2',
        title: 'Interactive JavaScript Tutorial',
        description: 'Hands-on JavaScript learning with live coding environment and real-time feedback',
        url: 'https://learnjavascript.online',
        type: 'interactive',
        learningStyle: 'kinesthetic',
        difficulty: 'beginner',
        duration: '15 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'hands-on',
        mastery: 'foundational',
        tags: ['javascript', 'interactive', 'coding', 'practice', 'exercises'],
        prerequisites: ['basic programming concepts'],
        outcomes: ['Code JavaScript confidently', 'Debug JavaScript programs', 'Use modern JavaScript features'],
        estimatedTime: 900,
        isProjectBased: false,
        isInteractive: true,
        hasExercises: true,
        language: 'JavaScript',
        skillLevel: 'novice'
      },
      {
        id: 'js-3',
        title: 'JavaScript Project: Build a Todo App',
        description: 'Create a complete todo application using vanilla JavaScript, HTML, and CSS',
        url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
        type: 'project',
        learningStyle: 'kinesthetic',
        difficulty: 'intermediate',
        duration: '8 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'project',
        mastery: 'intermediate-level',
        tags: ['javascript', 'project', 'todo-app', 'dom', 'local-storage'],
        prerequisites: ['JavaScript basics', 'HTML/CSS'],
        outcomes: ['Build a complete web application', 'Use local storage', 'Implement CRUD operations'],
        estimatedTime: 480,
        isProjectBased: true,
        isInteractive: true,
        hasExercises: false,
        language: 'JavaScript',
        skillLevel: 'intermediate'
      }
    ],
    'python': [
      {
        id: 'py-1',
        title: 'Python for Beginners',
        description: 'Learn Python programming from scratch with comprehensive examples and exercises',
        url: 'https://python.org/tutorial',
        type: 'course',
        learningStyle: 'reading',
        difficulty: 'beginner',
        duration: '25 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'tutorial',
        mastery: 'foundational',
        tags: ['python', 'programming', 'basics', 'syntax', 'data-types'],
        prerequisites: ['basic computer skills'],
        outcomes: ['Write Python programs', 'Use Python data structures', 'Handle file operations'],
        estimatedTime: 1500,
        isProjectBased: false,
        isInteractive: true,
        hasExercises: true,
        language: 'Python',
        skillLevel: 'novice'
      },
      {
        id: 'py-2',
        title: 'Python Visual Learning Guide',
        description: 'Python concepts explained with diagrams, flowcharts, and visual representations',
        url: 'https://realpython.com',
        type: 'course',
        learningStyle: 'visual',
        difficulty: 'intermediate',
        duration: '18 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'tutorial',
        mastery: 'intermediate-level',
        tags: ['python', 'visual', 'diagrams', 'algorithms', 'data-structures'],
        prerequisites: ['Python basics', 'programming concepts'],
        outcomes: ['Understand Python internals', 'Visualize algorithms', 'Optimize Python code'],
        estimatedTime: 1080,
        isProjectBased: false,
        isInteractive: true,
        hasExercises: true,
        language: 'Python',
        skillLevel: 'intermediate'
      },
      {
        id: 'py-3',
        title: 'Python Web Scraping Project',
        description: 'Build a web scraper to collect data from websites using BeautifulSoup and requests',
        url: 'https://scrapy.org',
        type: 'project',
        learningStyle: 'kinesthetic',
        difficulty: 'intermediate',
        duration: '12 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'project',
        mastery: 'intermediate-level',
        tags: ['python', 'web-scraping', 'beautifulsoup', 'requests', 'data-collection'],
        prerequisites: ['Python basics', 'HTML knowledge'],
        outcomes: ['Scrape web data', 'Parse HTML/XML', 'Handle dynamic content'],
        estimatedTime: 720,
        isProjectBased: true,
        isInteractive: true,
        hasExercises: false,
        language: 'Python',
        framework: 'BeautifulSoup',
        skillLevel: 'intermediate'
      }
    ],
    'react': [
      {
        id: 'react-1',
        title: 'React Official Tutorial',
        description: 'Learn React with interactive examples and step-by-step guided tutorials',
        url: 'https://reactjs.org/tutorial',
        type: 'tutorial',
        learningStyle: 'kinesthetic',
        difficulty: 'intermediate',
        duration: '12 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'tutorial',
        mastery: 'intermediate-level',
        tags: ['react', 'components', 'jsx', 'state', 'props'],
        prerequisites: ['JavaScript ES6', 'HTML/CSS', 'Node.js'],
        outcomes: ['Build React components', 'Manage component state', 'Use React lifecycle methods'],
        estimatedTime: 720,
        isProjectBased: true,
        isInteractive: true,
        hasExercises: true,
        language: 'JavaScript',
        framework: 'React',
        skillLevel: 'intermediate'
      },
      {
        id: 'react-2',
        title: 'React Visual Guide',
        description: 'React concepts with visual explanations, component trees, and data flow diagrams',
        url: 'https://react.dev',
        type: 'course',
        learningStyle: 'visual',
        difficulty: 'intermediate',
        duration: '16 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'tutorial',
        mastery: 'intermediate-level',
        tags: ['react', 'visual', 'components', 'hooks', 'context'],
        prerequisites: ['JavaScript ES6', 'React basics'],
        outcomes: ['Visualize React concepts', 'Use React hooks', 'Implement context API'],
        estimatedTime: 960,
        isProjectBased: false,
        isInteractive: true,
        hasExercises: true,
        language: 'JavaScript',
        framework: 'React',
        skillLevel: 'intermediate'
      },
      {
        id: 'react-3',
        title: 'Build a React E-commerce App',
        description: 'Create a complete e-commerce application with React, including cart, checkout, and user authentication',
        url: 'https://github.com/facebook/react',
        type: 'project',
        learningStyle: 'kinesthetic',
        difficulty: 'advanced',
        duration: '20 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'project',
        mastery: 'advanced-level',
        tags: ['react', 'e-commerce', 'authentication', 'state-management', 'api-integration'],
        prerequisites: ['React intermediate', 'Node.js', 'Database basics'],
        outcomes: ['Build complex React apps', 'Implement authentication', 'Integrate with APIs'],
        estimatedTime: 1200,
        isProjectBased: true,
        isInteractive: true,
        hasExercises: false,
        language: 'JavaScript',
        framework: 'React',
        skillLevel: 'advanced'
      }
    ],
    'machine learning': [
      // Visual Learning Resources
      {
        id: 'ml-v-1',
        title: 'Machine Learning Visual Guide - Deep Learning Specialization',
        description: 'Visual explanations of neural networks and deep learning with interactive diagrams and animations',
        url: 'https://www.coursera.org/specializations/deep-learning',
        type: 'course',
        learningStyle: 'visual',
        difficulty: 'beginner',
        duration: '25 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'tutorial',
        mastery: 'foundational',
        tags: ['machine-learning', 'deep-learning', 'neural-networks', 'visual', 'beginner'],
        prerequisites: ['Python basics'],
        outcomes: ['Understand neural networks visually', 'Build basic models', 'Visualize model training'],
        estimatedTime: 1500,
        isProjectBased: true,
        isInteractive: true,
        hasExercises: true,
        language: 'Python',
        framework: 'TensorFlow',
        skillLevel: 'novice'
      },
      {
        id: 'ml-v-2',
        title: '3Blue1Brown: Neural Networks Visualized',
        description: 'Beautiful visual explanations of how neural networks work with intuitive animations',
        url: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi',
        type: 'video',
        learningStyle: 'visual',
        difficulty: 'beginner',
        duration: '4 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'tutorial',
        mastery: 'foundational',
        tags: ['machine-learning', 'neural-networks', 'visual-explanations', 'youtube'],
        prerequisites: [],
        outcomes: ['Grasp neural network concepts intuitively', 'Understand backpropagation visually'],
        estimatedTime: 240,
        isProjectBased: false,
        isInteractive: false,
        hasExercises: false,
        language: 'Python',
        skillLevel: 'novice'
      },
      {
        id: 'ml-v-3',
        title: 'Google Machine Learning Crash Course',
        description: 'Interactive visual course with TensorFlow Playground and practical visualizations',
        url: 'https://developers.google.com/machine-learning/crash-course',
        type: 'interactive',
        learningStyle: 'visual',
        difficulty: 'intermediate',
        duration: '15 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'hands-on',
        mastery: 'intermediate-level',
        tags: ['machine-learning', 'tensorflow', 'interactive', 'visual-learning'],
        prerequisites: ['Python intermediate'],
        outcomes: ['Build and visualize ML models', 'Understand model performance metrics'],
        estimatedTime: 900,
        isProjectBased: true,
        isInteractive: true,
        hasExercises: true,
        language: 'Python',
        framework: 'TensorFlow',
        skillLevel: 'intermediate'
      },
      
      // Auditory Learning Resources
      {
        id: 'ml-a-1',
        title: 'Andrew Ng\'s Machine Learning Course (Audio Lectures)',
        description: 'Comprehensive ML course with detailed audio explanations and real-world applications',
        url: 'https://www.coursera.org/learn/machine-learning',
        type: 'course',
        learningStyle: 'auditory',
        difficulty: 'intermediate',
        duration: '60 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'theory',
        mastery: 'intermediate-level',
        tags: ['machine-learning', 'coursera', 'andrew-ng', 'lectures', 'algorithms'],
        prerequisites: ['Python basics', 'Linear algebra', 'Calculus'],
        outcomes: ['Master ML algorithms', 'Implement models from scratch', 'Optimize models'],
        estimatedTime: 3600,
        isProjectBased: true,
        isInteractive: true,
        hasExercises: true,
        language: 'Python',
        framework: 'NumPy',
        skillLevel: 'intermediate'
      },
      {
        id: 'ml-a-2',
        title: 'Machine Learning Podcast: Learning Machines 101',
        description: 'Audio podcast series explaining ML concepts in accessible language with case studies',
        url: 'https://www.learningmachines101.com/',
        type: 'course',
        learningStyle: 'auditory',
        difficulty: 'beginner',
        duration: '8 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'reference',
        mastery: 'introduction',
        tags: ['machine-learning', 'podcast', 'audio', 'beginner-friendly', 'casual-learning'],
        prerequisites: [],
        outcomes: ['Understand ML terminology', 'Learn real-world applications'],
        estimatedTime: 480,
        isProjectBased: false,
        isInteractive: false,
        hasExercises: false,
        language: 'English',
        skillLevel: 'newbie'
      },
      {
        id: 'ml-a-3',
        title: 'Fast.ai Deep Learning Lectures',
        description: 'Top-down approach to ML with audio lectures, starting with real problems and working backwards',
        url: 'https://course.fast.ai/',
        type: 'course',
        learningStyle: 'auditory',
        difficulty: 'intermediate',
        duration: '28 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'hands-on',
        mastery: 'intermediate-level',
        tags: ['deep-learning', 'practical', 'fast-ai', 'jeremy-howard', 'pytorch'],
        prerequisites: ['Python'],
        outcomes: ['Build state-of-the-art models', 'Understand deep learning practices'],
        estimatedTime: 1680,
        isProjectBased: true,
        isInteractive: true,
        hasExercises: true,
        language: 'Python',
        framework: 'PyTorch',
        skillLevel: 'intermediate'
      },
      
      // Reading/Writing Learning Resources
      {
        id: 'ml-r-1',
        title: 'Hands-On Machine Learning with Scikit-Learn & TensorFlow',
        description: 'Comprehensive book covering ML theory and practice with detailed code examples',
        url: 'https://www.oreilly.com/library/view/hands-on-machine-learning/9781492032632/',
        type: 'documentation',
        learningStyle: 'reading',
        difficulty: 'intermediate',
        duration: '40 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'reference',
        mastery: 'intermediate-level',
        tags: ['machine-learning', 'book', 'scikit-learn', 'tensorflow', 'deep-learning'],
        prerequisites: ['Python intermediate'],
        outcomes: ['Master ML fundamentals', 'Build production-ready models', 'Understand ML workflows'],
        estimatedTime: 2400,
        isProjectBased: true,
        isInteractive: true,
        hasExercises: true,
        language: 'Python',
        framework: 'Scikit-learn',
        skillLevel: 'intermediate'
      },
      {
        id: 'ml-r-2',
        title: 'Understanding Machine Learning: From Theory to Algorithms',
        description: 'Rigorous theoretical foundation for machine learning with mathematical proofs and examples',
        url: 'https://www.cs.huji.ac.il/~shais/UnderstandingMachineLearning/',
        type: 'documentation',
        learningStyle: 'reading',
        difficulty: 'advanced',
        duration: '50 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'theory',
        mastery: 'advanced-level',
        tags: ['machine-learning', 'theory', 'mathematics', 'algorithms', 'research'],
        prerequisites: ['Linear algebra', 'Probability theory', 'Calculus'],
        outcomes: ['Deep mathematical understanding', 'Prove ML theorems', 'Design new algorithms'],
        estimatedTime: 3000,
        isProjectBased: false,
        isInteractive: true,
        hasExercises: true,
        language: 'Python',
        skillLevel: 'advanced'
      },
      {
        id: 'ml-r-3',
        title: 'Machine Learning Yearning by Andrew Ng',
        description: 'Practical guide to applying ML in production with best practices and common pitfalls',
        url: 'https://www.mlyearning.org/',
        type: 'documentation',
        learningStyle: 'reading',
        difficulty: 'intermediate',
        duration: '6 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'reference',
        mastery: 'foundational',
        tags: ['machine-learning', 'practical', 'production', 'best-practices', 'andrew-ng'],
        prerequisites: ['ML basics'],
        outcomes: ['Deploy ML systems', 'Debug models', 'Improve model performance'],
        estimatedTime: 360,
        isProjectBased: true,
        isInteractive: false,
        hasExercises: false,
        language: 'English',
        skillLevel: 'intermediate'
      },
      
      // Kinesthetic Learning Resources
      {
        id: 'ml-k-1',
        title: 'Kaggle Learn: Intro to Machine Learning',
        description: 'Hands-on micro-courses with interactive coding exercises and competitions',
        url: 'https://www.kaggle.com/learn/intro-to-machine-learning',
        type: 'interactive',
        learningStyle: 'kinesthetic',
        difficulty: 'beginner',
        duration: '3 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'hands-on',
        mastery: 'foundational',
        tags: ['machine-learning', 'kaggle', 'pandas', 'scikit-learn', 'hands-on'],
        prerequisites: ['Python basics', 'Pandas basics'],
        outcomes: ['Build first ML model', 'Handle data cleaning', 'Submit to competitions'],
        estimatedTime: 180,
        isProjectBased: true,
        isInteractive: true,
        hasExercises: true,
        language: 'Python',
        framework: 'Scikit-learn',
        skillLevel: 'novice'
      },
      {
        id: 'ml-k-2',
        title: 'ML Project: Build a Recommendation System',
        description: 'Complete project tutorial creating a movie recommendation system from scratch',
        url: 'https://github.com/jadianes/spark-movie-lens',
        type: 'project',
        learningStyle: 'kinesthetic',
        difficulty: 'intermediate',
        duration: '10 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'project',
        mastery: 'intermediate-level',
        tags: ['machine-learning', 'recommendation-systems', 'collaborative-filtering', 'spark'],
        prerequisites: ['Python intermediate', 'ML basics'],
        outcomes: ['Build recommendation systems', 'Use Apache Spark', 'Deploy ML models'],
        estimatedTime: 600,
        isProjectBased: true,
        isInteractive: true,
        hasExercises: false,
        language: 'Python',
        framework: 'Apache Spark',
        skillLevel: 'intermediate'
      },
      {
        id: 'ml-k-3',
        title: 'Deep Learning Project: Image Generation with GANs',
        description: 'Build and train Generative Adversarial Networks to create realistic images',
        url: 'https://pytorch.org/tutorials/beginner/dcgan_faces_tutorial.html',
        type: 'project',
        learningStyle: 'kinesthetic',
        difficulty: 'advanced',
        duration: '20 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'project',
        mastery: 'advanced-level',
        tags: ['deep-learning', 'gans', 'generative-models', 'pytorch', 'computer-vision'],
        prerequisites: ['Deep learning intermediate', 'PyTorch', 'GPU basics'],
        outcomes: ['Train GANs', 'Generate synthetic images', 'Optimize model training'],
        estimatedTime: 1200,
        isProjectBased: true,
        isInteractive: true,
        hasExercises: false,
        language: 'Python',
        framework: 'PyTorch',
        skillLevel: 'advanced'
      },
      {
        id: 'ml-k-4',
        title: 'Natural Language Processing with Transformers',
        description: 'Hands-on guide to building NLP models using Hugging Face Transformers',
        url: 'https://huggingface.co/learn/nlp-course/',
        type: 'interactive',
        learningStyle: 'kinesthetic',
        difficulty: 'intermediate',
        duration: '18 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'hands-on',
        mastery: 'intermediate-level',
        tags: ['nlp', 'transformers', 'bert', 'gpt', 'hugging-face'],
        prerequisites: ['Python intermediate', 'ML basics'],
        outcomes: ['Build NLP models', 'Use pre-trained transformers', 'Fine-tune models'],
        estimatedTime: 1080,
        isProjectBased: true,
        isInteractive: true,
        hasExercises: true,
        language: 'Python',
        framework: 'Transformers',
        skillLevel: 'intermediate'
      },
      {
        id: 'ml-k-5',
        title: 'Reinforcement Learning by Doing',
        description: 'Build RL agents using OpenAI Gym and train them to solve classic control problems',
        url: 'https://gym.openai.com/',
        type: 'project',
        learningStyle: 'kinesthetic',
        difficulty: 'advanced',
        duration: '15 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'project',
        mastery: 'advanced-level',
        tags: ['reinforcement-learning', 'openai-gym', 'q-learning', 'policy-gradient'],
        prerequisites: ['Deep learning', 'Probability theory'],
        outcomes: ['Train RL agents', 'Implement RL algorithms', 'Solve control problems'],
        estimatedTime: 900,
        isProjectBased: true,
        isInteractive: true,
        hasExercises: false,
        language: 'Python',
        framework: 'PyTorch',
        skillLevel: 'advanced'
      },
      
      // Additional Mixed Style Resources
      {
        id: 'ml-mixed-1',
        title: 'MLflow: MLOps and Model Tracking Tutorial',
        description: 'Learn to manage ML lifecycle with versioning, tracking, and deployment tools',
        url: 'https://mlflow.org/docs/latest/tutorials-and-examples/tutorial.html',
        type: 'tutorial',
        learningStyle: 'kinesthetic',
        difficulty: 'intermediate',
        duration: '8 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'practice',
        mastery: 'intermediate-level',
        tags: ['mlops', 'model-deployment', 'experiment-tracking', 'mlflow'],
        prerequisites: ['ML intermediate'],
        outcomes: ['Track experiments', 'Deploy ML models', 'Manage ML pipelines'],
        estimatedTime: 480,
        isProjectBased: true,
        isInteractive: true,
        hasExercises: true,
        language: 'Python',
        framework: 'MLflow',
        skillLevel: 'intermediate'
      },
      {
        id: 'ml-mixed-2',
        title: 'Time Series Forecasting with ML',
        description: 'Build predictive models for time series data using ARIMA, LSTM, and Prophet',
        url: 'https://www.kaggle.com/learn/time-series',
        type: 'interactive',
        learningStyle: 'kinesthetic',
        difficulty: 'intermediate',
        duration: '5 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'hands-on',
        mastery: 'intermediate-level',
        tags: ['time-series', 'forecasting', 'lstm', 'statistics', 'kaggle'],
        prerequisites: ['ML intermediate', 'Pandas'],
        outcomes: ['Forecast time series', 'Use LSTM networks', 'Evaluate predictions'],
        estimatedTime: 300,
        isProjectBased: true,
        isInteractive: true,
        hasExercises: true,
        language: 'Python',
        framework: 'Scikit-learn',
        skillLevel: 'intermediate'
      },
      {
        id: 'ml-deep-1',
        title: 'Deep Learning Specialization',
        description: 'Comprehensive course on neural networks and deep learning, from fundamentals to advanced architectures',
        url: 'https://www.coursera.org/specializations/deep-learning',
        type: 'course',
        learningStyle: 'visual',
        difficulty: 'intermediate',
        duration: '35 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'tutorial',
        mastery: 'intermediate-level',
        tags: ['deep-learning', 'neural-networks', 'deep-learning-course', 'andrew-ng', 'coursera'],
        prerequisites: ['Python basics', 'Linear algebra', 'Machine learning basics'],
        outcomes: ['Understand neural networks', 'Build deep learning models', 'Train CNNs and RNNs'],
        estimatedTime: 2100,
        isProjectBased: true,
        isInteractive: true,
        hasExercises: true,
        language: 'Python',
        framework: 'TensorFlow',
        skillLevel: 'intermediate'
      },
      {
        id: 'ml-hands-on-1',
        title: 'Build a Complete ML Pipeline from Scratch',
        description: 'Hands-on tutorial creating an end-to-end machine learning pipeline with data preprocessing, feature engineering, and model deployment',
        url: 'https://www.kaggle.com/learn/intro-to-machine-learning',
        type: 'interactive',
        learningStyle: 'kinesthetic',
        difficulty: 'intermediate',
        duration: '12 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'hands-on',
        mastery: 'foundational',
        tags: ['machine-learning', 'hands-on', 'pipeline', 'kaggle', 'pandas', 'scikit-learn'],
        prerequisites: ['Python intermediate', 'Data analysis basics'],
        outcomes: ['Build complete ML pipelines', 'Preprocess data effectively', 'Deploy models'],
        estimatedTime: 720,
        isProjectBased: true,
        isInteractive: true,
        hasExercises: true,
        language: 'Python',
        framework: 'Scikit-learn',
        skillLevel: 'intermediate'
      },
      {
        id: 'ml-hands-on-2',
        title: 'Hands-On Machine Learning Workshop',
        description: 'Interactive coding workshop where you build and deploy real-world machine learning models with live coding sessions',
        url: 'https://course.fast.ai/',
        type: 'interactive',
        learningStyle: 'kinesthetic',
        difficulty: 'beginner',
        duration: '9 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'hands-on',
        mastery: 'foundational',
        tags: ['machine-learning', 'hands-on', 'workshop', 'interactive', 'practical'],
        prerequisites: ['Python basics'],
        outcomes: ['Code ML models hands-on', 'Understand practical ML', 'Build working applications'],
        estimatedTime: 540,
        isProjectBased: true,
        isInteractive: true,
        hasExercises: true,
        language: 'Python',
        framework: 'Fast.ai',
        skillLevel: 'novice'
      },
      {
        id: 'ml-poor-1',
        title: 'The Elements of Statistical Learning: Data Mining, Inference, and Prediction',
        description: 'Dense theoretical textbook covering statistical learning theory with mathematical rigor and minimal practical examples',
        url: 'https://web.stanford.edu/~hastie/ElemStatLearn/',
        type: 'book',
        learningStyle: 'reading',
        difficulty: 'advanced',
        duration: '80 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'theory',
        mastery: 'advanced-level',
        tags: ['machine-learning', 'statistics', 'theory', 'textbook', 'mathematical'],
        prerequisites: ['Linear algebra', 'Probability theory', 'Calculus', 'Statistics'],
        outcomes: ['Deep mathematical understanding', 'Prove statistical learning theorems', 'Understand theoretical foundations'],
        estimatedTime: 4800,
        isProjectBased: false,
        isInteractive: false,
        hasExercises: false,
        language: 'English',
        skillLevel: 'advanced'
      },
      {
        id: 'ml-poor-2',
        title: 'Machine Learning Research Papers Collection',
        description: 'Curated collection of advanced research papers on machine learning algorithms with heavy mathematical notation',
        url: 'https://arxiv.org/list/cs.LG/recent',
        type: 'documentation',
        learningStyle: 'reading',
        difficulty: 'advanced',
        duration: '60 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'reference',
        mastery: 'expert',
        tags: ['machine-learning', 'research', 'papers', 'academic', 'theory'],
        prerequisites: ['PhD-level mathematics', 'Advanced statistics', 'Research experience'],
        outcomes: ['Understand cutting-edge research', 'Read complex papers', 'Grasp theoretical advances'],
        estimatedTime: 3600,
        isProjectBased: false,
        isInteractive: false,
        hasExercises: false,
        language: 'English',
        skillLevel: 'expert'
      }
    ],
    'linear algebra': [
      {
        id: 'la-1',
        title: 'Linear Algebra Fundamentals',
        description: 'Complete introduction to linear algebra with visual explanations and interactive examples',
        url: 'https://khanacademy.org/math/linear-algebra',
        type: 'course',
        learningStyle: 'visual',
        difficulty: 'beginner',
        duration: '25 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'tutorial',
        mastery: 'foundational',
        tags: ['linear-algebra', 'mathematics', 'vectors', 'matrices', 'transformations'],
        prerequisites: ['basic algebra', 'geometry'],
        outcomes: ['Understand vectors and matrices', 'Solve linear equations', 'Apply transformations'],
        estimatedTime: 1500,
        isProjectBased: false,
        isInteractive: true,
        hasExercises: true,
        language: 'English',
        skillLevel: 'novice'
      },
      {
        id: 'la-2',
        title: 'Linear Algebra Interactive Tutorial',
        description: 'Hands-on linear algebra learning with interactive visualizations and step-by-step problem solving',
        url: 'https://www.3blue1brown.com/topics/linear-algebra',
        type: 'interactive',
        learningStyle: 'kinesthetic',
        difficulty: 'intermediate',
        duration: '20 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'hands-on',
        mastery: 'intermediate-level',
        tags: ['linear-algebra', 'interactive', 'visualizations', 'matrices', 'eigenvalues'],
        prerequisites: ['basic linear algebra', 'calculus'],
        outcomes: ['Visualize linear transformations', 'Understand eigenvalues', 'Apply matrix operations'],
        estimatedTime: 1200,
        isProjectBased: false,
        isInteractive: true,
        hasExercises: true,
        language: 'English',
        skillLevel: 'intermediate'
      },
      {
        id: 'la-3',
        title: 'Linear Algebra Applications',
        description: 'Real-world applications of linear algebra in computer graphics, machine learning, and data science',
        url: 'https://ocw.mit.edu/courses/mathematics/18-06-linear-algebra-spring-2010/',
        type: 'course',
        learningStyle: 'reading',
        difficulty: 'advanced',
        duration: '30 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'theory',
        mastery: 'advanced-level',
        tags: ['linear-algebra', 'applications', 'computer-graphics', 'machine-learning', 'data-science'],
        prerequisites: ['linear algebra intermediate', 'programming basics'],
        outcomes: ['Apply linear algebra to real problems', 'Understand ML applications', 'Use in computer graphics'],
        estimatedTime: 1800,
        isProjectBased: true,
        isInteractive: true,
        hasExercises: true,
        language: 'English',
        skillLevel: 'advanced'
      }
    ]
  }

  const topicKey = topic.toLowerCase()
  const specificResources = topicResources[topicKey] || []
  
  // Also include general resources that match the topic
  const generalResources = sampleResources.filter(resource => 
    resource.title.toLowerCase().includes(topic.toLowerCase()) ||
    resource.description.toLowerCase().includes(topic.toLowerCase()) ||
    resource.tags.some(tag => tag.toLowerCase().includes(topic.toLowerCase()))
  )

  // If no specific resources found, return some general educational resources
  if (specificResources.length === 0 && generalResources.length === 0) {
    return [
      {
        id: `general-${topic}-1`,
        title: `${topic.charAt(0).toUpperCase() + topic.slice(1)} Learning Resources`,
        description: `Comprehensive collection of resources for learning ${topic}`,
        url: 'https://khanacademy.org',
        type: 'course',
        learningStyle: 'visual',
        difficulty: 'beginner',
        duration: '15 hours',
        thumbnail: '/api/placeholder/300/200',
        category: 'tutorial',
        mastery: 'foundational',
        tags: [topic.toLowerCase(), 'learning', 'education', 'tutorial'],
        prerequisites: [],
        outcomes: [`Learn ${topic} fundamentals`, 'Build practical skills', 'Apply knowledge'],
        estimatedTime: 900,
        isProjectBased: false,
        isInteractive: true,
        hasExercises: true,
        language: 'English',
        skillLevel: 'novice'
      }
    ]
  }

  return [...specificResources, ...generalResources]
}